### PR TITLE
bad bug number regex, fixes #22

### LINKED ISSUE #22: Bug number regex matches commit SHA URL
The following commit:
https://github.com/mozilla/treeherder/commit/b37ef957a2282bcc7dd5d0d884df4b3c05718992

...was displayed in the what's deployed commit summary table like so:
`041510 - Update hawk from v6.0.2 to v7.0.5 (#3049)`

The `041510` isn't a valid bug number, but instead appears to have come from the following URL in the commit message:
`https://github.com/hueniverse/hawk/commit/f72cdeafd178bbd893e8c041510f2ecd733c0011#diff-04c6e90faac2675aa89e2176d2eec7d8L174`

### PR DESCRIPTION
**Pull request by peterbe**
@edmorley I wasn't able to reproduce it using treeherder's `revision.txt` but I copied the commit message [from the API](https://api.github.com/repos/mozilla/treeherder/commits/b37ef957a2282bcc7dd5d0d884df4b3c05718992) straight into the `main.js` and was able to reproduce and fix that way.

### CODE REVIEW

**Comment by edmorley** [comment]
Many thanks!

File: static/js/main.js [hunk 1]
```diff
@@ -37,9 +39,10 @@ function start(deployments, owner, repo, callback) {
   function bug_url(id) {
     return 'https://bugzilla.mozilla.org/show_bug.cgi?id=' + id;
   }
-  function bug_id(commit) {
-    var msg = commit.commit.message;
-    if (msg.match(/\d{6,7}/g)) return msg.match(/\d{6,7}/g)[0];
+  function bug_id(msg) {
+    if (msg.match(/\b\d{6,7}\b/g)) {
+      return msg.match(/\b\d{6,7}\b/g)[0];
+    }
```
Comment (ExE-Boss) [inline static/js/main.js]: This is horrendously inefficient.

You should instead do:
```js
function bug_id(msg) {
	let result = msg.match(/\b\d{6,7}\b/g);
	return Boolean(result) && result[0];
}
```

Comment (peterbe) [reply static/js/main.js]: I don't know about "horrendously" :)
I agree that it's inefficient in theory. At least in a purely mathematical way. 

Also, a prettier solution would probably be:

```javascript
let result = msg.match(/\b\d{6,7}\b/g);
return result && result[0] || false;
```
